version: '2'

services:
  db:
    # 当容器非正常退出后，尝试重启
    restart: always
    image: mysql:5.7.4
    volumes:
      - ./compose/mysql/my.cnf:/etc/my.cnf
      - ./db:/var/lib/mysql
    # for test
    ports:
      - "127.0.0.1:3307:3306"
      # (HOST:CONTAINER)
    env_file:
      - .env

  web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    command: ["/bin/bash", "gunicorn.sh"]
    # for test
    # ports:
    #  - "8000:8002"
    #  # (HOST:CONTAINER)
    volumes:
      - ./staticfiles:/code/staticfiles
      - ./logs:/var/log/
    depends_on:
      - db
    env_file: .env

  nginx:
    restart: always
    image: nginx:1.13.0
    volumes:
      - ./compose/nginx/:/etc/nginx/conf.d/
      - ./staticfiles:/code/staticfiles
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      # (HOST:CONTAINER)
    depends_on:
      - web
