# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180209_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_list', to='blogs.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='post_list', to='blogs.Tag', verbose_name='标签'),
        ),
    ]
