# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '正常'), ('remove', '删除')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '正常'), ('remove', '删除')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
