# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180514_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '正常'), (2, '删除')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '正常'), (2, '删除')], default=0, verbose_name='状态'),
        ),
    ]
