# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20180514_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
